# Generated by Django 4.2 on 2025-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.TextField(blank=True, default=""),
        ),
    ]
