# Generated by Django 4.2 on 2025-03-05 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_deleteduser_userselectedpath_profile_conversation"),
        ("accounts", "0002_user_tags"),
    ]

    operations = []
