# Generated by Django 4.2 on 2025-03-12 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeletedUser",
        ),
    ]
