# Generated by Django 4.2 on 2025-03-13 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_delete_deleteduser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userselectedpath",
            name="user",
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="UserSelectedPath",
        ),
    ]
