# Generated by Django 4.2 on 2025-03-10 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="message",
            new_name="bot_response",
        ),
        migrations.RenameField(
            model_name="chathistory",
            old_name="response",
            new_name="user_message",
        ),
    ]
