# Generated by Django 4.2 on 2025-03-10 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_rename_message_chathistory_bot_response_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="bot_response",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="chathistory",
            old_name="user_message",
            new_name="response",
        ),
    ]
