# Generated by Django 4.2 on 2025-03-15 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0003_rename_bot_response_chathistory_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chathistory",
            name="username",
        ),
        migrations.AddField(
            model_name="chathistory",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
